# Composite action for shared environment setup across all workflows.
# Eliminates duplicated Node/Python/uv setup.
#
# Usage:
#   - uses: ./.github/actions/setup
#   - uses: ./.github/actions/setup
#     with:
#       node-version: '22'
#       python-version: '3.11'

name: 'Setup MachinaOS Environment'
description: 'Setup Node.js, Python, and uv for cross-platform builds.'

inputs:
  node-version:
    description: 'Node.js version'
    default: '20'
  python-version:
    description: 'Python version'
    default: '3.12'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Verify installations
      shell: bash
      run: |
        echo "Node.js: $(node --version)"
        echo "npm: $(npm --version)"
        echo "Python: $(python --version)"
        echo "uv: $(uv --version)"
