// Filesystem & Shell Tool Nodes - Dual-purpose (workflow node + AI agent tool)
import { INodeTypeDescription, NodeConnectionType } from '../types/INodeProperties';

export const filesystemNodes: Record<string, INodeTypeDescription> = {
  fileRead: {
    displayName: 'File Read',
    name: 'fileRead',
    icon: '\u{1F4C4}',
    group: ['utility', 'tool'],
    version: 1,
    subtitle: 'Read File',
    description: 'Read file contents with line numbers and pagination. Works as workflow node or AI agent tool.',
    defaults: { name: 'File Read', color: '#8be9fd' },
    inputs: [{ name: 'main', displayName: 'Input', type: 'main' as NodeConnectionType, description: 'Input data' }],
    outputs: [
      { name: 'main', displayName: 'Output', type: 'main' as NodeConnectionType, description: 'File contents' },
      { name: 'tool', displayName: 'Tool', type: 'main' as NodeConnectionType, description: 'Connect to AI Agent tool handle' },
    ],
    properties: [
      {
        displayName: 'File Path',
        name: 'file_path',
        type: 'string' as any,
        default: '',
        required: true,
        description: 'Path to the file to read',
      },
      {
        displayName: 'Offset',
        name: 'offset',
        type: 'number' as any,
        default: 0,
        typeOptions: { minValue: 0 },
        description: 'Line number to start reading from (0-indexed)',
      },
      {
        displayName: 'Limit',
        name: 'limit',
        type: 'number' as any,
        default: 100,
        typeOptions: { minValue: 1, maxValue: 10000 },
        description: 'Maximum number of lines to read',
      },
    ],
  },

  fileModify: {
    displayName: 'File Modify',
    name: 'fileModify',
    icon: '\u{270F}\u{FE0F}',
    group: ['utility', 'tool'],
    version: 1,
    subtitle: 'Write / Edit File',
    description: 'Write a new file or edit an existing file with string replacement. Works as workflow node or AI agent tool.',
    defaults: { name: 'File Modify', color: '#50fa7b' },
    inputs: [{ name: 'main', displayName: 'Input', type: 'main' as NodeConnectionType, description: 'Input data' }],
    outputs: [
      { name: 'main', displayName: 'Output', type: 'main' as NodeConnectionType, description: 'Operation result' },
      { name: 'tool', displayName: 'Tool', type: 'main' as NodeConnectionType, description: 'Connect to AI Agent tool handle' },
    ],
    properties: [
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options' as any,
        default: 'write',
        options: [
          { name: 'Write', value: 'write' },
          { name: 'Edit', value: 'edit' },
        ],
        description: 'Write creates/overwrites a file. Edit performs string replacement.',
      },
      {
        displayName: 'File Path',
        name: 'file_path',
        type: 'string' as any,
        default: '',
        required: true,
        description: 'Path to the file',
      },
      {
        displayName: 'Content',
        name: 'content',
        type: 'string' as any,
        default: '',
        typeOptions: { rows: 5 },
        description: 'File content to write',
        displayOptions: { show: { operation: ['write'] } },
      },
      {
        displayName: 'Old String',
        name: 'old_string',
        type: 'string' as any,
        default: '',
        typeOptions: { rows: 3 },
        description: 'Exact text to find and replace',
        displayOptions: { show: { operation: ['edit'] } },
      },
      {
        displayName: 'New String',
        name: 'new_string',
        type: 'string' as any,
        default: '',
        typeOptions: { rows: 3 },
        description: 'Text to replace old_string with',
        displayOptions: { show: { operation: ['edit'] } },
      },
      {
        displayName: 'Replace All',
        name: 'replace_all',
        type: 'boolean' as any,
        default: false,
        description: 'Replace all occurrences (default: first only, old_string must be unique)',
        displayOptions: { show: { operation: ['edit'] } },
      },
    ],
  },

  shell: {
    displayName: 'Shell',
    name: 'shell',
    icon: '\u{1F4BB}',
    group: ['utility', 'tool'],
    version: 1,
    subtitle: 'Execute Command',
    description: 'Execute shell commands and return stdout, stderr, and exit code. Works as workflow node or AI agent tool.',
    defaults: { name: 'Shell', color: '#ff79c6' },
    inputs: [{ name: 'main', displayName: 'Input', type: 'main' as NodeConnectionType, description: 'Input data' }],
    outputs: [
      { name: 'main', displayName: 'Output', type: 'main' as NodeConnectionType, description: 'Command output' },
      { name: 'tool', displayName: 'Tool', type: 'main' as NodeConnectionType, description: 'Connect to AI Agent tool handle' },
    ],
    properties: [
      {
        displayName: 'Command',
        name: 'command',
        type: 'string' as any,
        default: '',
        required: true,
        typeOptions: { rows: 3 },
        description: 'Shell command to execute',
      },
      {
        displayName: 'Timeout (seconds)',
        name: 'timeout',
        type: 'number' as any,
        default: 30,
        typeOptions: { minValue: 1, maxValue: 300 },
        description: 'Maximum execution time in seconds',
      },
    ],
  },

  fsSearch: {
    displayName: 'FS Search',
    name: 'fsSearch',
    icon: '\u{1F50D}',
    group: ['utility', 'tool'],
    version: 1,
    subtitle: 'List / Glob / Grep',
    description: 'Search the filesystem: list directories, glob pattern match, or grep file contents. Works as workflow node or AI agent tool.',
    defaults: { name: 'FS Search', color: '#f1fa8c' },
    inputs: [{ name: 'main', displayName: 'Input', type: 'main' as NodeConnectionType, description: 'Input data' }],
    outputs: [
      { name: 'main', displayName: 'Output', type: 'main' as NodeConnectionType, description: 'Search results' },
      { name: 'tool', displayName: 'Tool', type: 'main' as NodeConnectionType, description: 'Connect to AI Agent tool handle' },
    ],
    properties: [
      {
        displayName: 'Mode',
        name: 'mode',
        type: 'options' as any,
        default: 'ls',
        options: [
          { name: 'List Directory', value: 'ls' },
          { name: 'Glob Pattern', value: 'glob' },
          { name: 'Grep Contents', value: 'grep' },
        ],
        description: 'Search mode: list directory, glob file patterns, or grep file contents',
      },
      {
        displayName: 'Path',
        name: 'path',
        type: 'string' as any,
        default: '.',
        description: 'Directory path to search in',
      },
      {
        displayName: 'Pattern',
        name: 'pattern',
        type: 'string' as any,
        default: '',
        description: 'Glob pattern (e.g., **/*.py) or grep search text',
        displayOptions: { show: { mode: ['glob', 'grep'] } },
      },
      {
        displayName: 'File Filter',
        name: 'file_filter',
        type: 'string' as any,
        default: '',
        description: 'Glob pattern to filter which files to grep (e.g., *.py)',
        displayOptions: { show: { mode: ['grep'] } },
      },
    ],
  },
};

export const FILESYSTEM_NODE_TYPES = ['fileRead', 'fileModify', 'shell', 'fsSearch'];
